accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
  path('', views.index, name='index'),
  path('signup/', views.signup, name='signup'),
  path('login/', views.login, name='login'),
  path('logout/', views.logout, name='logout'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/follow/', views.follow, name='follow'),
  path('update/', views.update, name='update'),
  path('<int:pk>/withdraw/', views.withdraw, name='withdraw'),
  path('password/', views.password_edit, name='password_edit'),  
]

django_pair5/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
    path("", include("index.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path("", views.index, name="index"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:pk>/c_create", views.c_create, name="c_create"),
    path("<int:a_pk>/<int:c_pk>/c_delete", views.c_delete, name="c_delete"),
    path("like/<int:pk>", views.like, name="like"),
]

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    grade = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        blank=True,
        upload_to="images/",
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_reviews"
    )


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = {
            "title",
            "content",
            "movie_name",
            "grade",
            "image",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

reviews/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):

    reviews = Review.objects.order_by("-pk")

    context = {
        "reviews": reviews,
    }
    return render(request, "reviews/index.html", context)


@login_required
def create(request):

    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("reviews:index")
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }

    return render(request, "reviews/create.html", context)


def detail(request, pk):

    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = review.comment_set.order_by("-pk")

    context = {
        "review": review,
        "comment_form": comment_form,
        "comments": comments,
    }

    return render(request, "reviews/detail.html", context)


def delete(request, pk):

    review = Review.objects.get(pk=pk)
    review.delete()

    return redirect("reviews:index")


@login_required
def update(request, pk):

    review = Review.objects.get(pk=pk)

    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect("reviews:detail", pk)
    else:
        review_form = ReviewForm(instance=review)
    context = {
        "review_form": review_form,
        "review": review,
    }

    return render(request, "reviews/update.html", context)


def c_create(request, pk):

    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()

    return redirect("reviews:detail", pk)


@login_required
def c_delete(request, a_pk, c_pk):

    comment = Comment.objects.get(pk=c_pk)
    comment.delete()

    return redirect("reviews:detail", a_pk)


def like(request, pk):

    review = Review.objects.get(pk=pk)

    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
    else:
        review.like_users.add(request.user)

    return redirect("reviews:index")

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1 class='text-center my-3'>글쓰기 페이지</h1><hr>

<form action='' method='POST' enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% bootstrap_button button_type='submit' content='글쓰기' %}
</form>


{% endblock body %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<hr>

<li>작성자: <a href="{% url 'accounts:detail' review.user.pk %}">{{ review.user }}</a></li>
<li>작성시간 {{ review.created_at }}</li>
<li>리뷰 영화: {{ review.movie_name }}</li>
<li>평점: {{ review.grade }}</li>
<hr>
<h1 class='text-center'>{{ review.title }}</h1>
<p>{{ review.content }}<p>
{% if review.image %}
<div class='text-center'>
  <img src="{{ review.image.url }}" alt="{{ review.image }}">
</div>
{% endif %}
{% if request.user == review.user %}
<div class='d-grid gap-2 my-4'>
  <a class='btn btn-outline-success btn-sm' href="{% url 'reviews:update' review.pk %}">수정하기</a>
  <a class='btn btn-outline-danger btn-sm' href="{% url 'reviews:delete' review.pk %}">삭제하기</a>
</div>
{% endif %}
<hr>
{% if request.user.is_authenticated %}
  <form action="{% url 'reviews:c_create' review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form layout="inline" %}
    {% bootstrap_button button_type="submit" content="댓글작성" %}
  </form>
{% endif %}
<h3 class='text-center'>댓글 목록</h3>
<hr>
{% for comment in comments %}
  <p>{{ comment.user }}  |  {{ comment.created_at }}  |  {{ comment.content }}  |  
    {% if request.user.is_authenticated %}
      {% if request.user == comment.user%}
        <a href="{% url 'reviews:c_delete' review.pk comment.pk %}">삭제</a>
      {% endif %}
    {% endif %}
  </p>
{% empty %}
  <p>댓글이 없습니다 ㅠㅠ</p>
{% endfor %}

{% endblock body %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load imagekit %}

{% block body %}
<hr>
{% if request.user.is_authenticated %}
<div class='text-end'>
  <a class='btn btn-primary btn-sm my-1' href="{% url 'reviews:create' %}">글쓰기</a>
</div>
{% endif %}

<div class='d-flex align-content-around justify-content-between flex-wrap my-2'>
  {% for review in reviews %}
  <div class="card my-2 border-secondary" style="width: 14rem; ">
    {% if review.image %}
      {% thumbnail "200x167" review.image as thumb %}
      <img src="{{ review.image.url }}" class="card-img-top" alt="{{ review.image }}" height="{{ thumb.height }}">
    {% else %}
      <img src="https://picsum.photos/200/150" class="card-img-top" alt="imagefile">
    {% endif %}
    <div class="card-body">
      <div class='d-flex justify-content-between'>
          <p class="card-text fw-bold">{{ review.user }}</p>
          <p class="card-text">No.{{ review.pk }}</p>
      </div>
      <div class='py-3'>
        <h4 class="card-title"><a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a></h4>
      </div>
      <div class='text-end'>
        {% if request.user in review.like_users.all %}
        <a href="{% url 'reviews:like' review.pk %}" class="btn btn-danger btn-sm">♥ {{ review.like_users.count }} </a>
        {% else %}
          <a href="{% url 'reviews:like' review.pk %}" class="btn btn-outline-danger btn-sm">♥ {{ review.like_users.count }} </a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<hr>

{% endblock body %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1 class='text-center my-3'>글수정 페이지</h1><hr>

<form action='' method='POST' enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% bootstrap_button button_type='submit' content='수정' %}
</form>
<div class='text-end'>
  <a href="{% url 'reviews:detail' review.pk %}">뒤로가기</a>
</div>


{% endblock body %}