accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
  path('', views.index, name='index'),
  path('signup/', views.signup, name='signup'),
  path('login/', views.login, name='login'),
  path('logout/', views.logout, name='logout'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/follow/', views.follow, name='follow'),
  path('update/', views.update, name='update'),
  path('<int:pk>/withdraw/', views.withdraw, name='withdraw'),
  path('password/', views.password_edit, name='password_edit'),  
]

django_pair5/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
    path("", include("index.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path("", views.index, name="index"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:pk>/c_create", views.c_create, name="c_create"),
    path("<int:a_pk>/<int:c_pk>/c_delete", views.c_delete, name="c_delete"),
    path("like/<int:pk>", views.like, name="like"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.

class User(AbstractUser):
  followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
  image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(400, 300)],
                                format='JPEG',
                                options={'quality': 80})

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    grade = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        blank=True,
        upload_to="images/",
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_reviews"
    )


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "image",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
        )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

# 회원가입 form import
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import get_user_model

# login, logout 내장 form import
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# 회원인증
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

# 메시지알림
from django.contrib import messages

# 로그인되어야지만 들어가지게 설정
from django.contrib.auth.decorators import login_required

# 비밀번호 변경
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

# Create your views here.


@login_required
def index(request):
    user = get_user_model().objects.all()
    context = {"user": user}
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()  # ModelForm의 save 메서드의 리턴값은 해당 모델의 인스턴스다!
            auth_login(request, user)  # 로그인
            messages.success(request, "회원가입이 되었습니다.")
            return redirect("accounts:login")

    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {"user": user}
    return render(request, "accounts/detail.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    messages.warning(request, "로그아웃 하였습니다.")
    return redirect("reviews:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


def withdraw(request, pk):
    get_user_model().objects.get(id=pk).delete()
    return redirect("accounts:index")


def follow(request, pk):
    # 프로필에 해당하는 유저를 로그인한 유저가!
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user == user:
        messages.warning(request, "스스로 팔로우 할 수 없습니다.")
        return redirect("accounts:detail", pk)
    if request.user in user.followers.all():
        # (이미) 팔로우 상태이면, '팔로우 취소'버튼을 누르면 삭제 (remove)
        user.followers.remove(request.user)
    else:
        # 팔로우 상태가 아니면, '팔로우'를 누르면 추가 (add)
        user.followers.add(request.user)
    return redirect("accounts:detail", pk)


@login_required
def password_edit(request):
    if request.method == "POST":

        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Password successfully changed")
            return redirect("accounts:login")
        else:
            messages.error(request, "Password not changed")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "accounts/password.html", {"form": form})

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}
<div class="row my-4">
  <div class="col-4">
      {% if user.image %}
      <img src="{{ user.image.url }}" alt="{{ user.image }}" width="400" height="300">
      {% endif %}
  </div>
  <div class="col-8">
    <div class="row">  
      <h1 class="m-0 mr-3">ID : {{ user.username }}</h1>
      <br>
      <h3>이름 : {{ user.last_name }} {{ user.first_name }}</h3>
    </div>
    <div class="row">      
      {% if request.user != user %}
      <p class="m-0 mx-1">
      <a class="btn btn-primary text-decoration-none" href="{% url 'accounts:follow' user.pk %}">
      {% if request.user in user.followers.all %}
      팔로우 취소
      {% else %}
      팔로우
      {% endif %}
      </a>
      </p>
      {% endif %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col-6">
    {% if request.user == user %}     
    <a class="btn btn-outline-dark text-decoration-none" href="{% url 'accounts:update' %}" role="button">프로필수정</a>
    <a class="btn btn-outline-dark text-decoration-none" href="{% url 'accounts:password_edit' %}" role="button">비밀번호변경</a>
    <a class="btn btn-outline-danger text-decoration-none" href="{% url 'accounts:withdraw' user.pk %}" role="button">회원탈퇴</a>
    {% endif %}
  </div>
</div>

<div class="row my-4">
  <div class="col-6 d-flex justify-content-start mx-4">
    <p>팔로우 : {{ user.followings.count }} | 팔로워 : {{ user.followers.count }}</p>
  </div>
</div>

<div class="row">
  <div class="col-6">
      <h3>작성한 글</h3>
      <p class="text-muted">{{ user.review_set.count }}개를 작성하였습니다.</p>
      {% for review in user.review_set.all %}
      <p>
          {{ forloop.counter }}
          <a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
      </p>
      {% endfor %}
  </div>
  <div class="col-6">
      <h3>작성한 댓글</h3>
      <p class="text-muted">{{ user.comment_set.count }}개를 작성하였습니다.</p>
      {% for comment in user.comment_set.all %}
      <p>
          {{ forloop.counter }}
          <a href="{% url 'reviews:detail' comment.review_id %}">{{ comment.content }}</a>
      </p>
      {% endfor %}
  </div>
</div>


{% comment %} <div class="row">
  <div class="col-6 d-flex justify-content-start mx-4">
    {% if request.user != user %}
    <a href="{% url 'accounts:follow' user.pk %}">
        {% if request.user in user.followers.all %}
            팔로우 취소
        {% else %}
            팔로우
        {% endif %}
    </a>
    {% endif %}
  </div>
</div> {% endcomment %}


{% endblock body %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block body %}
<div class="text-center my-5">
  <h1>회원목록</h1>
</div>

<div class="row d-flex justify-content-center">
  <div class="col-6">
    <div class="p-5">
      <table class="table">
        <thead class="table-info">
          <tr>
            <th scope="col">pk</th>
            <th scope="col">username</th>
          </tr>
        </thead>
        {% for u in user %}
        <tbody>
          <tr>
            <th scope="row">{{ u.pk}}</th>
            <td><a href="{% url 'accounts:detail' u.pk %}">{{ u.username }}</a></td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>
  </div>
</div>

{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block body %}
<div class="text-center my-5">
  <h1>로그인</h1>
</div>

<div class="row d-flex justify-content-center">
  <div class="col-6">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="OK" %}
    </form>
  </div>
</div>
{% endblock body %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block body %}

<div class="text-center my-5">
  <h1>비밀번호 변경</h1>
</div>

<div class="container">
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="비밀번호변경" %}
  </form>
</div>

{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block body %}
<div class="text-center my-5">
<h1>회원가입</h1>
</div>

<div class="row d-flex justify-content-center">
    <div class="col-12">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="OK" %}
        </form>
    </div>
</div>

{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block body %}
<h1>프로필 업데이트</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock body %}