django_pair5/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
    path("", include("index.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path("", views.index, name="index"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:pk>/c_create", views.c_create, name="c_create"),
    path("<int:a_pk>/<int:c_pk>/c_delete", views.c_delete, name="c_delete"),
    path("like/<int:pk>", views.like, name="like"),
]

index/templates/index/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MovieReview</title>
        <!-- Favicon-->
        <link rel="icon" href="{% static '/moviefavicon.ico' %}" type="image/x-icon">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Callout-->
        <section class="callout">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mx-auto mb-5">
                    Welcome to<br>
                    <em>our website</em>
                </h2>
                <a class="btn btn-primary btn-xl" href="{% url 'reviews:index' %}">ENTER!!</a>
            </div>
        </section>
        <footer class="footer text-center">
          <div class="container px-4 px-lg-5">
              <ul class="list-inline">
                  <li class="list-inline-item">
                      <a class="social-link rounded-circle text-white mr-3" href="https://github.com/soohofather"><i class="icon-social-github"></i></a>
                  </li>
                  <li class="list-inline-item">
                      <a class="social-link rounded-circle text-white" href="https://github.com/yoosoonil"><i class="icon-social-github"></i></a>
                  </li>
              </ul>
              <p class="text-muted small mb-0">Copyright &copy; 이동현, 유순일</p>
              <p class="text-muted small mb-0">2022.10.28</p>
          </div>
      </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>